### ISSUE TITLE
bc2pg - track date downloaded

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcdata#86]
Either:
- create a `bcdata` meta table with columns `table_name`, `date_downloaded` or similar
- add a generated `date_downloaded` column to the downloaded table

1 seems a lot more space efficient but 2 is super easy

**Comment by NewGraphEnvironment** [comment]
I wonder if it might be worth it to use the `record_last_modified` metadata from bc data catalog rather than (or as well as) the date of download.... It seems as though records are not always updated each day so this might allow different users to reference when they have the same dataset in their databases.

**Comment by smnorris** [comment]
AFAIK that data isn't reliable enough to be useful.

**Comment by smnorris** [comment]
My recent thought was to add a switch to `bc2pg` for how often to download the dataset. I could check the `date_downloaded` column in the `bcdata` table and if the data is stale, download a new copy.

Something like `--interval D` for always download a new version daily. `--interval M` for only download if it hasn't been downloaded in a month, or maybe this calendar month. Etc

**Comment by NewGraphEnvironment** [comment]
Switches are a great idea
